apiVersion: v1
kind: Service
metadata:
  name: address-book-service
spec:
  selector:
    app: address-book # Selects pods with the label "app: address-book"
  ports:
    - protocol: TCP
      port: 8080 # The port the service listens on
      targetPort: 8080 # The port on the pod to forward traffic to
  type: LoadBalancer # Exposes the service externally (e.g., via a cloud load balancer)